config/routes.rb
Rails.application.routes.draw do
  # get 'top/index'
  root "top#index"
  post "income_values/new(/:name)" => "income_values#new"

  resources :incomes
  resources :fixedcosts
  resources :variablecosts
  resources :income_values
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
end

app/models/form/income_form.rb
class Form::IncomeForm < Form::Base
	attr_accessor :income_values

	def initialize(attributes = {})
    super attributes
		incomes = Income.order(created_at: :asc)
		selP.income_values = incomes.map { |income| IncomeValue.new(income_id: income.id) } unless income_values.present?
  end

	def income_values_attributes=(attributes)
    self.income_values = attributes.map do |_, income_value_attributes|
      Form::IncomeValue.new(income_value_attributes).tap { |v| puts v}
    end

  end

	def valid?
		valid_income_values = self.income_values.map(&:valid?).all?
		super && valid_income_values
	end

	def save
		return false unless valid?
		IncomeValue.transaction {
			self.income_values.select.each { |income_value|
				a1 = IncomeValue.new(:income_id => income_value.income_id,
					:year_month => income_value.year_month,
					:value => income_value.value,
					:description => income_value.description)
				a1.save!
			 }
		}
		true
	end

	def target_income_values
		self.income_values.select { |v| '*' }
	end

end

app/models/form/income_value.rb
class Form::IncomeValue < IncomeValue
	REGISTRABLE_ATTRIBUTES = %i(income_id year_month value description)
	attr_accessor :income_id
	attr_accessor :year_month
	attr_accessor :value
	attr_accessor :description
end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_values, dependent: :destroy
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord
end

app/models/variablecost.rb
class Variablecost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController

  def index
    @fixedcosts = Fixedcost.order(created_at: :asc)
  end

  def show
    @fixedcost = Fixedcost.find(params[:id])
  end

  def new
    @fixedcost = Fixedcost.new()
  end

  def edit
    @fixedcost = Fixedcost.find(params[:id])
  end

  def create
    @fixedcost = Fixedcost.new(params[:fixedcosts])
    if @fixedcost.save
      redirect_to @fixedcost, notice: "固定費科目を登録しました"
    else
      render "new"
    end
  end

  def update
    @fixedcost = Fixedcost.find([:id])
    @fixedcost.assign_attributes(params[:fixedcost])
    if @fixedcost.save
      redirect_to @fixedcost, notice: "固定費科目を登録しました"
    else
      render "new"
    end
  end

  def destroy
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.destroy
    rdirect_to :fixedcosts, notice: "科目を削除しました"
  end
end

app/controllers/income_values_controller.rb
class IncomeValuesController < ApplicationController

  def index
    @incomes = Income.order(created_at: :asc)
    @income_values = IncomeValue.order("year_month asc")
  end

  def show
    @income_value = IncomeValue.find(params[:id])
  end

  def new
    year_month_day = params[:year_month] + "-01"
    @year_month = year_month_day.to_date

    @incomes = Income.order(created_at: :asc)
    @form = Form::IncomeForm.new
  end

  def edit
    @income_value = IncomeValue.find(params[:id])
    @income = Income.find(@income_value.income_id)
  end

  def create
    @form = Form::IncomeForm.new(income_form_params)
    if @form.save
      redirect_to :income_values, notice: "登録しました"
    else
      redirect_to :income_values, notice: "登録に失敗しました"
    end
  end

  def income_form_params
    params
      .require(:form_income_form)
      .permit(income_values_attributes: Form::Income::REGISTRABLE_ATTRIBUTES)
  end

  def update
    @income_value = IncomeValue.find(params[:id])
    @income_value.assign_attributes(params[:income_value])
    if @income_value.save
      redirect_to :income_values, notice: "情報を更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @income_value = IncomeValue.find(params[:id])
    @income_value.destroy
    redirect_to :income_values, notice: "データを削除しました"
  end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  def index
    @incomes = Income.order(created_at: :asc)
  end

  def show
    @income = Income.find(params[:id])
  end

  def new
    @income = Income.new()
  end

  def edit
    @income = Income.find(params[:id])
  end

  def create
    @income = Income.new(params[:income])
    if @income.save
      redirect_to @income, notice: "収入科目を登録しました"
    else
      render "new"
    end
  end

  def update
    @income = Income.find(params[:id])
    @income.assign_attributes(params[:income])
    if @income.save
      redirect_to @income, notice: "収入科目を登録しました"
    else
      render "new"
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    redirect_to :incomes, notice: "科目を削除しました"
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/variablecosts_controller.rb
class VariablecostsController < ApplicationController

  def index
    @variablecosts = Variablecost.order(created_at: :asc)
  end

  def show
    @variablecost = Variablecost.find(params[:id])
  end

  def new
    @variablecost = Variablecost.new()
  end

  def edit
    @variablecost = Variablecost.find(params[:id])
  end

  def created
    @variablecost = Variablecost.new(params[:variablecost])
    if variablecost.save
      redirect_to @variablecost, notice: "変動費科目を登録しました"
    else
      render "new"
    end
  end

  def update
    @variablecost = Variablecost.find(params[id])
    @variablecost.assign_attributes(params[:variablecost])
    if @variablecost.save
      redirect_to @variablecost, notice: "変動費科目を登録しました"
    else
      render "new"
    end
  end

  def destroy
    @variablecost = Variablecost.find(params[:id])
    @variablecost.destroy
    redirect_to :variablecosts, notice: "科目を削除しました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/income_values_helper.rb
module IncomeValuesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/variablecosts_helper.rb
module VariablecostsHelper
end

app/views/fixedcosts/_form.html.erb
<%= link_to "固定費科目一覧に戻る", :fixedcosts %>
<table>
  <tr>
    <th><%= form.label :name, "名称" %></th>
    <td><%= form.text_field :name %></td>
  </tr>
  <tr>
    <th><%= form.label :description, "説明" %></th>
    <td><%= form.text_field :description %></td>
  </tr>
</table>

app/views/fixedcosts/edit.html.erb
<h2>固定費科目編集</h2>
<%= form_with @fexedcost do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/fixedcosts/index.html.erb
<% @page_title = "固定費科目一覧" %>
<h2><%= @page_title %></h2>

<%= link_to "固定費科目の新規投稿", :new_fixedcost %>

<% if @fixedcosts.present? %>
<table>
  <thead>
    <tr>
      <th>科目名</th>
      <th>備考</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @fixedcosts.each do |fixedcost| %>
      <tr>
        <td><%= fixedcost.name %></td>
        <td><%= fixedcost.description %></td>
        <td>
        <%= link_to "編集", [:edit,fixedcost] %>
        <%= link_to "削除", fixedcost, method: :delete, data: { confirm: "本当に削除してもよろしいでしょうか？"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <p>登録されている固定費科目がありません</p>
<% end %>

app/views/fixedcosts/new.html.erb
<h2>固定費科目登録</h2>
<%= fotm_with @fixedcost do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/fixedcosts/show.html.erb
<h2>固定費科目詳細</h2>

<%= link_to "編集", [:edit, @fixedcost] %>
<%= link_to "固定費科目一覧へ戻る", :fixedcosts %>

<table>

  <tr>
    <th>名称</th>
    <td><%= @fixedcost.name %></td>
  </tr>

  </tr>
    <th>説明</th>
    <td><%= @fixedcost.description %></td>
  </tr>
</table>

app/views/income_values/edit.html.erb
<h2>収支科目 データ修正 </h2>

	<%= form_for @income_value do |form| %>
		<table>
			<tr>
				<th>登録日</th>
		    <th>名称</th>
		    <th>値</th>
		    <th>備考</th>
		  </tr>

		  <tr>
			  <td><%= form.date_select :year_month, start_year: 2010, end_year: Time.current.year,
	 						 use_month_numbers: true, discard_day: true %></td>
			  <th><%= @income.name %></th>
	 		  <td><%= form.text_field :value %></td>
	 		  <td><%= form.text_field :description %></td>
		  </tr>
		</table>
		<div><%= form.submit %></div>
	<% end %>

app/views/income_values/index.html.erb
<% require 'active_support/core_ext/numeric/conversions' %>
<h2>収入科目の新規データ登録</h2>
<p>登録年月を設定してください</p>
<%= form_tag({controller: :income_values, action: :new}, {method: :post}) do %>
	<input type="month" name="year_month">
	<input type="submit">
<% end %>

<h2>収入科目 データ一覧 </h2>
<% if @income_values.present? %>
  <table>
      <tr>
        <th>登録年月</th>
        <th>名称</th>
        <th>値</th>
        <th>備考</th>
		    <th>操作</th>
      </tr>
	  <% @income_values.each do |income_value| %>
	    <tr>
		    <td><%= income_value.year_month.strftime('%Y年%m月') %></td>
		    <td><%= @incomes.find(income_value.income_id).name %></td>
		    <td><%= income_value.value.to_s(:delimited) %> 円</td>
		    <td><%= income_value.description %></td>
		    <td>
		      <%= link_to "編集", [:edit, income_value] %> |
		      <%= link_to "削除", income_value, method: :delete, data: { confirm: "本当に削除しますか？"} %>
		    </td>
	    </tr>
	  <% end %>
  </table>
<% else %>
	<p>登録されているデータがありません。</p>
<% end %>

app/views/income_values/new.html.erb
<% @page_title = "収入科目 データ登録" %>
<h2><%= @page_title %></h2>
<div class="toolbar"><%= link_to "収入科目データ一覧に戻る", :income_values %></div>
<%= form_for(@form, url: income_values_path, method: :post) do |fb| %>

  <!-- 年月テーブル -->
  <table>
    <tr>
      <th>登録年月</th>
      <th>名称</th>
      <th>値</th>
      <th>備考</th>
    </tr>

    <% cnt=0 %>
    <%= fb.fields_for :income_values do |f| %>
      <%= f.hidden_field :income_id %>

      <tr>
	  	  <td>
          <%= f.date_select :year_month, start_year: 2010, end_year: Time.current.year,
						  use_month_numbers: true, discard_day: true, default: @year_month %>
        </td>

        <th>
          <%= @incomes.find(@form.income_values[cnt].income_id).name %>
        </th>
        <% cnt+=1 %>
        <td><%= f.text_field :value, size: 8 %></td>
        <td><%= f.text_field :description, size: 8 %></td>

      </tr>
    <% end %>
  </table>

  <div><%= fb.submit %></div>
<% end %>

app/views/income_values/show.html.erb
<h1>show</h1>

app/views/incomes/_form.html.erb
<%= link_to "収入科目一覧に戻る", :incomes %>
<table>
  <tr>
    <th><%= form.label :name, "名称" %></th>
    <td><%= form.text_field :name %></td>
  </tr>
  <tr>
    <th><%= form.label :description, "説明" %></th>
    <td><%= form.text_field :description %></td>
  </tr>
</table>

app/views/incomes/edit.html.erb
<h2>収入科目編集</h2>
<%= form_with @income do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/incomes/index.html.erb
<% @page_title = "収入科目一覧" %>
<h2><%= @page_title %></h2>

<%= link_to "収入科目の新規登録", :new_income %>

<% if @incomes.present? %>
<table>
  <thead>
    <tr>
      <th>科目名</th>
      <th>備考</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.name %></td>
        <td><%= income.description %></td>
        <td>
        <%= link_to "編集", [:edit, income] %>
        <%= link_to "削除", income, method: :delete, data: { confirm: "本当に削除してもよろしいでしょうか？"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <p>登録されている収入科目がありません。</p>
<% end %>

app/views/incomes/new.html.erb
<h2>収入科目登録</h2>
<%= form_for @income do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/incomes/show.html.erb
<h2>収入科目明細</h2>

<%= link_to "編集", [:edit, @income] %>
<%= link_to "収入科目一覧へ戻る" %>

<table>

    <tr>
      <th>名称</th>
      <td><%= @income.name %></td>
    </tr>

    <tr>
      <th>説明</th>
      <td><%= @income. description %></td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HKノート</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= link_to "新規登録", "#", class: 'icon__new' %>

      <%= yield %>
    
  </body>
</html>

app/views/top/index.html.erb
<h1>HKノート</h1>
<p>シンプルな家計簿です</p>

<h2>科目設定</h2>
<ul>
  <li><%= link_to "収入科目設定", :incomes %></li>
</ul>

<ul>
  <li><%= link_to "固定費科目設定", :fixedcosts %></li>
</ul>

<ul>
  <li><%= link_to "変動費科目設定", :variablecosts %></li>
</ul>

<h2>収支登録</h2>
<ul>
	<li><%= link_to "収入金額登録", :income_values %></li>
</ul>

app/views/variablecosts/_form.html.erb
<%= link_to "変動費科目一覧に戻る", :variablecosts %>
<table>
  <tr>
    <th><%= form.label :name, "名称" %></th>
    <td><%= form.text_field :name %></td>
  </tr>
  <tr>
    <th><%= form.label :description, "説明" %></th>
    <td><%= form.text_field :description %></td>
  </tr>
</table>

app/views/variablecosts/edit.html.erb
<h2>変動費科目編集</h2>
<%= from_with @variablecost do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/variablecosts/index.html.erb
<% @page_title = "変動費科目一覧" %>
<h2><%= @page_title %></h2>

<%= link_to "変動費科目の新規登録", :new_variablecost %>

<% if @variablecosts.present? %>
<table>
  <thead>
    <tr>
      <th>科目名</th>
      <th>備考</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @variablecosts.each do |variablecost| %>
      <tr>
        <td><%= variablecost.name %></td>
        <td><%= variablecost.description %></td>
        <td>
          <%= link_to "編集", [:edit, variablecost] %>
          <%= link_to "削除", variablecost, method: :delete, data: { confirm: "本当に削除してもよろしいでしょうか" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <p>登録されている変動費科目がありません</p>
<% end %>

app/views/variablecosts/new.html.erb
<h2>変動費科目登録</h2>
<%= from_with @variablecost do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/variablecosts/show.html.erb
<h2>変動費科目の詳細</h2>

<%= link_to "編集", [:edit, @variablecost] %>
<%= link_to "変動費科目一覧へ戻る", :variablecosts %>

<table>

  <tr>
    <th>名称</th>
    <td><%= @variablecost.name %></td>
  </tr>

  <tr>
    <th>説明</th>
    <td><%= @variablecost.description %></td>
  </tr>
</table>